### ISSUE TITLE
Grouping Avaya Results in Kibana

### ISSUE THREAD

**Issue by daviojm** [OzWookiee/avaya-smdr-elasticstack#1]
Hey OzWookiee, so been using the ELK stack for 3 weeks now. Getting the data into elasticsearch and viewing it using Kibana. Where I'm stuck at, is getting the report or view that I want from the data using Kibana.

Basically just want to view all outgoing external calls made and sort them by the duration descending. I have it filtered with just "call_type = outgoing external call".
But sorting by the duration in the Discover tab doesn't seem to work. Neither sorting by Connected Time.

Can't seem to Group by Call ID, which would help if the calls got transferred multiple times.

I have looked through your config files and don't seem to see any configuration that would help in that regards.

You got any tips?

**Comment by OzWookiee** [comment]
TotalCallTimeSecs is the field you want. Make sure that you set the field in Kibana as a time (can't remember the exact at the moment)
