### ISSUE TITLE
Dashboards are referencing some missing visualizations

### ISSUE THREAD

**Issue by Ivan-WeTHINK** [OzWookiee/avaya-smdr-elasticstack#2]
Hey, thanks for sharing this! It's Awesome! 

Took me a while to familiarize myself with the ELK stack, and then another bit to update some things to the latest version 7.7, but I managed to get it "partially" working. 

I noticed some of your dashboards are referencing visualizations that are not part of the export files, for example, your dashboard "AroFlo Calls" is referencing "Calls-Total", which is missing from the visualizations file "export-3-visualization.json".

If it's of any use to you, I can export the new files using the latest export format (JSON will also be discontinued) and with the changes I've made to make it work on 7.7, because they have removed document types within indexes.

**Comment by Ivan-WeTHINK** [comment]
BTW, this is also happening to a lot of additional visualizations, such as:

- Calls-by-User
- Calls-by-Department
- Calls-by-Total-Call-Time
- Calls-by-DialledNumber
- etc.

I wonder if this could be related to some of them having data from your internal organization structure, but some don't seem to refer to anything like that. Anyway... if you could share a few, or upload an updated version, it would be great! Thanks!

**Comment by OzWookiee** [comment]
Hmmm ok I'll review and see about exporting again :D

**Comment by OzWookiee** [comment]
OK If you do a pull I just did an export from our ELK7.6 Kibana for all of the Calls2 (I had to redo them all with the change to 7.x)

**Comment by Ivan-WeTHINK** [comment]
Sorry OzWeekiee, been off for a while. Thanks a lot for uploading this, I have imported the new visualizations but now I am having a few issues with what it looks to be a new index structure. 

Any chance you can also update your logstash and elastic definitions? 

Thanks much! And sorry for the annoyances!

**Comment by OzWookiee** [comment]
https://github.com/OzWookiee/avaya-smdr-elasticstack/blob/master/elasticsearch/smdr-mapping-elasticsearch.json updated
